version: "3.8"

services:
  db:
    image: mariadb:10.4.24
    container_name: firemap_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    container_name: firemap_api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    command: "api"
    ports:
      - "8081:8081"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - HTTP_SERVER_PORT=8081
      - CLOUDINARY_URL=${CLOUDINARY_URL}

  migrations:
    container_name: firemap_migrations
    build:
        context: .
        dockerfile: ./api/Dockerfile
    command: "migrate"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  nginx:
    container_name: firemap_nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:8080"
    environment:
      API_HOST: ${API_HOST}

volumes:
  db_data:
